# Makefile to start odoo
# 
# Author: siavava <amittaijoel@outlook.com>

start:
	make -C /workspace/work/odoo start

config:
	make -C /workspace/work/odoo config

stop:
	make -C /workspace/work/odoo stop

clean:
	make -C /workspace/work/odoo clean
