# Makefile to start odoo
# 
# Author: siavava <amittaijoel@outlook.com>

start:
	make -C ../odoo_config start

config:
	make -C ../odoo_config config

stop:
	make -C ../odoo_config stop

clean:
	make -C ../odoo_config clean
